<a href="https://colab.research.google.com/github/RamSakamuri/Python_60Days/blob/main/1_Text_Representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduciton to NLP

NLP is a subfield of computer science and artificial intelligence concerned with interactions between computers and human (natural) languages. It is used to apply machine learning algorithms to text and speech.
For example, we can use NLP to create systems like speech recognition, document summarization, machine translation, spam detection, named entity recognition, question answering, autocomplete, predictive typing and so on.
Nowadays, most of us have smartphones that have speech recognition. These smartphones use NLP to understand what is said. Also, many people use laptops which operating system has a built-in speech recognition.


# Libraries

If you are familiar with python you know there is at least one library for everything in NLP ther are many!

## NLTK
![alt text](https://i2.wp.com/clay-atlas.com/wp-content/uploads/2019/08/python_nltk.png)

NLTK is one of the leading platform for building Python programs to work with human language data. It provides easy-to-use interfaces to over 50 corpora and lexical resources such as WordNet, along with a suite of text processing libraries for classification, tokenization, stemming, tagging, parsing, and semantic reasoning, wrappers for industrial-strength NLP libraries.

It's very popular in accademia nad implements many different algorithms, but lacks more modern approaces 


In [ ]:
# !pip install nltk
# !pip install pyspellchecker
# !pip install spacy
# !pip install gensim
# !pip install transformers
# !pip install spacymoji

import nltk
# In your local machine you will have a nice interface
nltk.download()

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/



## Spacy
![alt text](https://spacy.io/static/social_default-1d3b50b1eba4c2b06244425ff0c49570.jpg)

SpaCy is a free and open-source library for Natural Language Processing (NLP) in Python with a lot of in-built capabilities. It’s becoming increasingly popular for processing and analyzing data in NLP. Unstructured textual data is produced at a large scale, and it’s important to process and derive insights from unstructured data. To do that, you need to represent the data in a format that can be understood by computers. NLP can help you do that.



In [ ]:
# to download models and data for the English language
!python -m spacy download en_core_web_sm
import spacy
nlp = spacy.load('en_core_web_sm')

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
2023-05-09 13:13:10.902813: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-09 13:13:13.076997: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-05-09 13:13:15.682270: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-05-09 13:13:15.682925: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node rea


## Gensim
![alt text](https://repository-images.githubusercontent.com/1349775/202c4680-8f7c-11e9-91c6-745fdcbeffe8)


Gensim is a Python library for topic modelling, document indexing and similarity retrieval with large corpora. Target audience is the natural language processing (NLP) and information retrieval (IR) community.

Features
- All algorithms are memory-independent w.r.t. the corpus size (can process input larger than RAM, streamed, out-of-core),
- Intuitive interfaces
easy to plug in your own input corpus/datastream (simple streaming API)
easy to extend with other Vector Space algorithms (simple transformation API)
- Efficient multicore implementations of popular algorithms, such as online Latent Semantic Analysis (LSA/LSI/SVD), Latent Dirichlet Allocation (LDA), Random Projections (RP), Hierarchical Dirichlet Process (HDP) or word2vec deep learning.
- Distributed computing: can run Latent Semantic Analysis and Latent Dirichlet Allocation on a cluster of computers.

The type of input Gensim supports:
* As sentences stored in python’s native list object
* As one single text file, small or large.
* In multiple text files.


The core concepts of gensim are:

- Document: some text.
- Corpus: a collection of documents.
- Vector: a mathematically convenient representation of a document.
- Model: an algorithm for transforming vectors from one representation to another.

Read more in the [documentation](https://radimrehurek.com/gensim/auto_examples/core/run_core_concepts.htm).

In [ ]:
from gensim import corpora

document = "Human machine interface for lab abc computer applications"

text_corpus = [
    "Human machine interface for lab abc computer applications",
    "A survey of user opinion of computer system response time",
    "The EPS user interface management system",
    "System and human system engineering testing of EPS",
    "Relation of user perceived response time to error measurement",
    "The generation of random binary unordered trees",
    "The intersection graph of paths in trees",
    "Graph minors IV Widths of trees and well quasi ordering",
    "Graph minors A survey",
]

# Lowercase each document, split it by white space and filter out stopwords
texts = [[word for word in document.lower().split()]
         for document in text_corpus]

print(texts)
dictionary = corpora.Dictionary(texts)

new_vec = dictionary.doc2bow(document.lower().split())
print(new_vec)


[['human', 'machine', 'interface', 'for', 'lab', 'abc', 'computer', 'applications'], ['a', 'survey', 'of', 'user', 'opinion', 'of', 'computer', 'system', 'response', 'time'], ['the', 'eps', 'user', 'interface', 'management', 'system'], ['system', 'and', 'human', 'system', 'engineering', 'testing', 'of', 'eps'], ['relation', 'of', 'user', 'perceived', 'response', 'time', 'to', 'error', 'measurement'], ['the', 'generation', 'of', 'random', 'binary', 'unordered', 'trees'], ['the', 'intersection', 'graph', 'of', 'paths', 'in', 'trees'], ['graph', 'minors', 'iv', 'widths', 'of', 'trees', 'and', 'well', 'quasi', 'ordering'], ['graph', 'minors', 'a', 'survey']]
[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1)]


In [ ]:
new_vec

[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1)]



## GloVe
![alt text](https://miro.medium.com/max/594/0*zjSn1J3eqTXzTxDI.jpg)

 GloVe is an unsupervised learning algorithm for obtaining vector representations for words. Training is performed on aggregated global word-word co-occurrence statistics from a corpus, and the resulting representations showcase interesting linear substructures of the word vector space.

The main intuition underlying the model is the simple observation that ratios of word-word co-occurrence probabilities have the potential for encoding some form of meaning. 


In [ ]:
# WARNING: some of the files are quite large
# You can also manually downlaod the pre-trained 
# wectors and data are here: https://drive.google.com/drive/folders/1Mm3lk1DqIatS08rTVLlO1IxC2drXjCGG?usp=sharing
# from Stanford NLP group https://nlp.stanford.edu/projects/glove/.

from google.colab import drive
import numpy as np

drive.mount('/content/drive')

# Change it with your own path
path = '/content/drive/My Drive/Colab Notebooks/DL/input/'
comp = 'hate-speech-classification/'
EMBEDDING_FILE=f'{path}glove.6B.50d.txt'
TRAIN_DATA_FILE=f'{path}{comp}train.csv'
TEST_DATA_FILE=f'{path}{comp}test.csv'


embed_size = 50 # how big is each word vector
max_features = 20000 # how many unique words to use (i.e num rows in embedding vector)
maxlen = 100 # max number of words in a comment to use

# each line of the file looks like this:
# business 0.023693 0.13316 0.023131 ...

# Creating a dictionary {word: embedding}
embeddings_dict = {}
with open(EMBEDDING_FILE, 'r') as f:
    lines = [f.readline() for x in range(2)]
    for line in lines:
        values = line.split()
        word = values[0]
        vector = np.asarray(values[1:], "float32")
        embeddings_dict[word] = vector




Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
embeddings_dict

{'the': array([ 4.1800e-01,  2.4968e-01, -4.1242e-01,  1.2170e-01,  3.4527e-01,
        -4.4457e-02, -4.9688e-01, -1.7862e-01, -6.6023e-04, -6.5660e-01,
         2.7843e-01, -1.4767e-01, -5.5677e-01,  1.4658e-01, -9.5095e-03,
         1.1658e-02,  1.0204e-01, -1.2792e-01, -8.4430e-01, -1.2181e-01,
        -1.6801e-02, -3.3279e-01, -1.5520e-01, -2.3131e-01, -1.9181e-01,
        -1.8823e+00, -7.6746e-01,  9.9051e-02, -4.2125e-01, -1.9526e-01,
         4.0071e+00, -1.8594e-01, -5.2287e-01, -3.1681e-01,  5.9213e-04,
         7.4449e-03,  1.7778e-01, -1.5897e-01,  1.2041e-02, -5.4223e-02,
        -2.9871e-01, -1.5749e-01, -3.4758e-01, -4.5637e-02, -4.4251e-01,
         1.8785e-01,  2.7849e-03, -1.8411e-01, -1.1514e-01, -7.8581e-01],
       dtype=float32),
 ',': array([ 0.013441,  0.23682 , -0.16899 ,  0.40951 ,  0.63812 ,  0.47709 ,
        -0.42852 , -0.55641 , -0.364   , -0.23938 ,  0.13001 , -0.063734,
        -0.39575 , -0.48162 ,  0.23291 ,  0.090201, -0.13324 ,  0.078639,
        -0.4

## Huggingface


![alt text](https://huggingface.co/favicon.ico)

A group that is pushing innovative methods in NLP, in particular transformers, an evolution of word2vect.

We will use SimpleTransformer (https://github.com/ThilinaRajapakse/simpletransformers) wich is based on huggingface Transformer.

Also provide ultra-fast tokenizatoin using deep learning (Encode 1GB in 20sec).

In [ ]:
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
tokenizer.tokenize("I'm a new GPU!")

['i', "'", 'm', 'a', 'new', 'gp', '##u', '!']

# Stopwords, stemming, One-Hot Encoding, and more.

## What are Stopwords?
Stopwords are the most common words in any natural language. For the purpose of analyzing text data and building NLP models, these stopwords might not add much value to the meaning of the document.


Generally, the most common words used in a text are “the”, “is”, “in”, “for”, “where”, “when”, “to”, “at” etc.



Consider this text string – “There is a pen on the table”. Now, the words “is”, “a”, “on”, and  “the” add no meaning to the statement while parsing it. Whereas words like “there”, “book”, and “table” are the keywords and tell us what the statement is all about


## When should we remove stopwords

It's usuallly a good idea to remove stopwords in the following tasks:

- Text Classification
- Spam Filtering
- Language Classification
- Genre Classification
- Caption Generation
- Auto-Tag Generation
 

Avoid Stopword Removal
- Machine Translation
- Language Modeling
- Text Summarization
- Question-Answering problems




## Stopwords, list vs fewquency

In general a mojaor problem in NLP is data sparsness. To combat that a common solution si to eliminate all non-useful information and reduce the ammount of useful information.

Advantages in removing Stopwords:

- less noise (no info)
- less data
- better oerfirmances
- training time and storage needs decease


Disadvantages:: 

- can completely change the sentence meaning.

This pizza is not good can becaome: "pizza good" 


### list

There are several known issues in ‘english’ stop word list. It does not aim to be a general, ‘one-size-fits-all’ solution as some tasks may require a more custom solution.


Please take care in choosing a stop word list. Popular stop word lists may include words that are highly informative to some tasks, such as computer.


You should also make sure that the stop word list has had the same preprocessing and tokenization applied as the one used in the vectorizer. The word we’ve is split into we and ve by CountVectorizer’s default tokenizer, so if we’ve is in stop_words, but ve is not, ve will be retained from we’ve in transformed text. Scikits learn's vectorizers will try to identify and warn about some kinds of inconsistencies

Moreover scikits learn only have english stopwords, for completeness we will use NLTK stopwords so it will be easier for you to use it in other languages.

### Frequency

Another approach is using the fact that stopwords by definition are very common. Therefore it's possible to eliinate them by looking at their frequency.


These removal can also create problems. For example how do we establish what's the fequence to identify the stopwords, and how are we going to be sure we will remove alls stopwords?


Scikits learn implements several algorithms to count word and token frequency in an efficient way.

In Countvectorizer https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html  it's possible to pass the stopwords as an argument. If None, no stop words will be used. max_df can be set to a value in the range [0.7, 1.0) to automatically detect and filter stop words based on intra corpus document frequency of terms.
![alt text](https://www.educative.io/api/edpresso/shot/5197621598617600/image/6596233398321152)

In practice more we will create an index to increase efficiency.

![alt text](https://kavita-ganesan.com/wp-content/uploads/image-5.png)


if you wnat to be even more efficient you can use HashingVectorizer. This text vectorizer implementation uses the hashing trick to find the token string name to feature integer index mapping.


This strategy has several advantages:

- it is very low memory scalable to large datasets as there is no need to store a vocabulary dictionary in memory

- it is fast to pickle and un-pickle as it holds no state besides the constructor parameters

- it can be used in a streaming (partial fit) or parallel pipeline as there is no state computed during fit.

There are also a couple of cons (vs using a CountVectorizer with an in-memory vocabulary):

- there is no way to compute the inverse transform (from feature indices to string feature names) which can be a problem when trying to introspect which features are most important to a model.

- there can be collisions: distinct tokens can be mapped to the same feature index. However in practice this is rarely an issue if n_features is large enough (e.g. 2 ** 18 for text classification problems).

- no IDF weighting as this would render the transformer stateful.



## Examples
Let's now see some example, we will start by loading the "20 newsgroups" dataset in scikits learn.

In [ ]:
from sklearn.datasets import fetch_20newsgroups

categories = ['alt.atheism', 'soc.religion.christian',
              'comp.graphics', 'sci.med']

twenty_train = fetch_20newsgroups(subset='train', 
                                  categories=categories,
                                  shuffle=True,
                                  random_state=11)

twenty_test = fetch_20newsgroups(subset='test',
                                 categories=categories,
                                 shuffle=True,
                                 random_state=11)


twenty_train.keys()

sample_text = twenty_train.data[1]
sample_text

'From: jcopelan@nyx.cs.du.edu (The One and Only)\nSubject: Re: Where are they now?\nOrganization: Salvation Army Draft Board\nLines: 31\n\nIn article <1ql0d3$5vo@dr-pepper.East.Sun.COM> geoff@East.Sun.COM writes:\n>Your posting provoked me into checking my save file for memorable\n>posts. The first I captured was by Ken Arromdee on 19 Feb 1990, on the\n>subject "Re: atheist too?". That was article #473 here; your question\n>was article #53766, which is an average of about 48 articles a day for\n>the last three years. As others have noted, the current posting rate is\n>such that my kill file is depressing large...... Among the posting I\n>saved in the early days were articles from the following notables:\n>\n>>From: loren@sunlight.llnl.gov (Loren Petrich)\n>>From: jchrist@nazareth.israel.rel (Jesus Christ of Nazareth)\n>>From: mrc@Tomobiki-Cho.CAC.Washington.EDU (Mark Crispin)\n>>From: perry@apollo.HP.COM (Jim Perry)\n>>From: lippard@uavax0.ccit.arizona.edu (James J. Lippard)\n>>From: m

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(twenty_train.data)
print(vectorizer.get_feature_names_out()[-3:])
print(X.toarray()[-3:])

vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))
X2 = vectorizer2.fit_transform(twenty_train.data)
print(vectorizer2.get_feature_names_out()[-3:])
print(X2.toarray()[-3:])

['zzz' 'ªl' 'íålittin']
[[0 0 0 ... 0 0 0]
 [0 4 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
['zyxel v32bis' 'ªl r0506048' 'íålittin no']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


## Tokenizer

Given a character sequence and a defined document unit, tokenization is the task of chopping it up into pieces, called tokens , often removing punctuation. Here is an example of tokenization:

Input: "This is the best movie of all time."


Output: ["This" "is" "the" "best" "movie" "of" "all" "time"]

In [ ]:
import nltk
nltk.download('punkt')
sample_text = 'this is an,example'
text_tokens = nltk.word_tokenize(sample_text)
text_tokens

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


['this', 'is', 'an', ',', 'example']

In [ ]:
nltk.download('stopwords')
from nltk.corpus import stopwords
# caching stopwords improves performance
stopwords_list = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


Stopwords removal has to be done before stemming. Since some of stopwords in a text should be stemmed by a stemmer and cannot be filtered by given stopwords anymore. For example, "was" turns into "wa" by porter stemmer and when you stemmed first before removing stopwords "wa" remains in your vector after filtering stopwords which has "was" as a stopword. Alternatively, you can run the same stemmer on your set stopwords and then process with stopwords on stemmed text. I'm not sure if there's a tool implicitly runs stemming on given stopwords list to serve there masters, but basically it is not a good idea to put stemming on stopwords because stopwords are not always just a list of tokens from a natural language like english but sometimes they are domain specific words or some others given by practicians and cannot be judged by such toolkits. Therefore, removing stopwords in original form must be done before running stemmer.


We need to m

In [ ]:
[i for i in ['no', 'No', 'I', 'fly'] if i not in stopwords_list] 

['No', 'I', 'fly']

In [ ]:
[i for i in ['no', 'No', 'I', 'fly'] if i.lower() not in stopwords_list] 

['fly']

In [ ]:
[i for i in text_tokens if i.lower() not in stopwords_list]

[',', 'example']

## Gensim

In [ ]:
from gensim.parsing.preprocessing import remove_stopwords, preprocess_string, strip_tags, strip_punctuation

remove_stopwords("Better late than never, but better never late.")
# u'Better late never, better late.'

# create some

CUSTOM_FILTERS = [lambda x: x.lower(), strip_tags, strip_punctuation]

processed_string = preprocess_string(sample_text, CUSTOM_FILTERS)
processed_string

['this', 'is', 'an', 'example']

# Sklearn

Stopwords removal can be done inside some algoritms, like CountVectorizer

## CountVectorizer

Convert a collection of text documents to a matrix of token counts

This implementation produces a sparse representation of the counts using scipy.sparse.csr_matrix.

If you do not provide an a-priori dictionary and you do not use an analyzer that does some kind of feature selection then the number of features will be equal to the vocabulary size found by analyzing the data.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords 
stopwords_list = ['the', 'a', 'where']
vectorizer = CountVectorizer(stop_words=stopwords_list)
X = vectorizer.fit_transform(twenty_train.data[:3])
print(vectorizer.get_feature_names_out())
print(X.toarray())

['14' '19' '1990' '1993apr19' '1ql0d3' '21652' '231641' '31' '473' '48'
 '53766' '5vo' 'about' 'accepted' 'actor' 'address' 'afterwards' 'alt'
 'among' 'an' 'and' 'animation' 'anyone' 'anything' 'anywhere' 'apollo'
 'are' 'arizona' 'army' 'arromdee' 'article' 'articles' 'as' 'aspect' 'at'
 'atheism' 'atheist' 'au' 'average' 'b64635' 'be' 'beaverton' 'board'
 'branch' 'bucaille' 'bunch' 'but' 'by' 'cac' 'can' 'captured' 'case'
 'caused' 'cc' 'ccit' 'changed' 'checking' 'cho' 'christ' 'colleague'
 'com' 'commonly' 'compound' 'cranford' 'crispin' 'cs' 'current' 'curse'
 'cwru' 'darice' 'davidian' 'day' 'days' 'dead' 'depressing' 'didn'
 'disney' 'dkoresh' 'dr' 'draft' 'du' 'early' 'east' 'edu' 'either' 'even'
 'every' 'faith' 'fear' 'feb' 'file' 'find' 'first' 'fly' 'following'
 'followup' 'for' 'fred' 'freedom' 'from' 'galacticentric' 'genocide'
 'geocentrism' 'geoff' 'get' 'god' 'gov' 'has' 'have' 'he' 'hear' 'heart'
 'heliocentric' 'here' 'his' 'history' 'host' 'hp' 'if' 'in' 'inc'
 'i

## Stemming

For grammatical reasons, documents are going to use different forms of a word, such as organize, organizes, and organizing. Additionally, there are families of derivationally related words with similar meanings, such as democracy, democratic, and democratization. In many situations, it seems as if it would be useful for a search for one of these words to return documents that contain another word in the set.

The goal of both stemming and lemmatization is to reduce inflectional forms and sometimes derivationally related forms of a word to a common base form. For instance:

am, are, is $\Rightarrow$ be
car, cars, car's, cars' $\Rightarrow$ car
The result of this mapping of text will be something like:
the boy's cars are different colors $\Rightarrow$
the boy car be differ color

In [ ]:
from nltk.stem import PorterStemmer, SnowballStemmer

ps = PorterStemmer()
ps.stem('apples')

'appl'

In [ ]:
ps = SnowballStemmer('english')
ps.stem('are')

'are'

In [ ]:
stemmed_words = [ps.stem(w) for w in processed_string]
stemmed_words

['this', 'is', 'an', 'exampl']

## Stemming with Gensim

In [ ]:
from gensim.parsing.porter import PorterStemmer
p = PorterStemmer()
p.stem_sentence("apple files")

'appl file'

In [ ]:
p.stem_sentence(sample_text)

'thi is an,exampl'

In [ ]:
p.stem_documents(twenty_train.data[:3])

['from: mikec@sail.labs.tek.com (micheal cranford) subject: disnei anim organization: tektronix, inc., beaverton, or. lines: 5 ------------------------------------ can anyon tell me anyth about the disnei anim softwar package? note the followup line (thi is not for me but for a colleague).',
 'from: jcopelan@nyx.cs.du.edu (the on and only) subject: re: where ar thei now? organization: salvat armi draft board lines: 31 in articl <1ql0d3$5vo@dr-pepper.east.sun.com> geoff@east.sun.com writes: >your post provok me into check my save file for memor >posts. the first i captur wa by ken arromde on 19 feb 1990, on the >subject "re: atheist too?". that wa articl #473 here; your question >wa articl #53766, which is an averag of about 48 articl a dai for >the last three years. as other have noted, the current post rate is >such that my kill file is depress large...... among the post i >save in the earli dai were articl from the follow notables: > >>from: loren@sunlight.llnl.gov (loren petrich) >>

## Enhancing Scikits Learn 



Fancy token-level analysis such as stemming, lemmatizing, compound splitting, filtering based on part-of-speech, etc. are not included in the scikit-learn codebase, but can be added by customizing either the tokenizer or the analyzer. Here’s a CountVectorizer with a tokenizer and lemmatizer using NLTK.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from gensim.parsing.porter import PorterStemmer
from nltk import word_tokenize          
from nltk.stem import WordNetLemmatizer 

ps = PorterStemmer()

# from nltk.stem import PorterStemmer 

ps.stem_sentence('apple files')


class StemTokenizer:
    def __init__(self):
        self.ps = PorterStemmer()
    def __call__(self, doc):
        return [self.ps.stem(t) for t in word_tokenize(doc)]

vect = CountVectorizer(tokenizer=StemTokenizer())  


X = vect.fit_transform(twenty_train.data[:3])
print(vect.get_feature_names_out())


['#' '$' "''" '(' ')' ',' '--' '.' '....' '......' '14' '19' '1990'
 '1993apr19.231641.21652' '1ql0d3' '2' '31' '473' '48' '5' '53766' '5vo'
 ':' ';' '<' '>' '?' '@' '``' 'a' 'about' 'accept' 'actor' 'address'
 'afterward' 'alt.messian' 'among' 'an' 'and' 'anim' 'anyon' 'anyth'
 'anywher' 'apollo.hp.com' 'ar' 'armi' 'arromde' 'articl' 'as' 'aspect'
 'at' 'atheism' 'atheist' 'averag' 'b64635.student.cwru.edu' 'be'
 'beaverton' 'board' 'branch.davidian.compound.waco.tx.u' 'bucail' 'bunch'
 'but' 'by' 'can' 'captur' 'case' 'caus' 'chang' 'check' 'christ'
 'colleagu' 'commonli' 'cranford' 'crispin' 'current' 'curs' 'dai' 'daric'
 'dead' 'depress' 'did' 'disnei' 'dkoresh' 'dr-pepper.east.sun.com' 'dr.'
 'draft' 'earli' 'east.sun.com' 'either' 'even' 'everi' 'faith' 'fear'
 'feb' 'file' 'find' 'first' 'fly' 'follow' 'followup' 'for' 'fred'
 'freedom' 'from' 'galacticentr' 'genocid' 'geocentr' 'geoff' 'get' 'god'
 'ha' 'have' 'he' 'hear' 'heart' 'heliocentr' 'here' 'hi' 'histori' 'i'
 'if' 'i

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


Or even more fancy lemmatizers...

In [ ]:
nltk.download('wordnet')

class LemmaTokenizer:
    def __init__(self):
        self.wnl = WordNetLemmatizer()
    def __call__(self, doc):
        return [self.wnl.lemmatize(t) for t in word_tokenize(doc)]

vect = CountVectorizer(tokenizer=LemmaTokenizer())  

X = vect.fit_transform(twenty_train.data[:3])
print(vect.get_feature_names_out())

['#' '$' "''" '(' ')' ',' '--' '.' '....' '......' '14' '19' '1990'
 '1993apr19.231641.21652' '1ql0d3' '2' '31' '473' '48' '5' '53766' '5vo'
 ':' ';' '<' '>' '?' '@' '``' 'a' 'about' 'accepted' 'actor' 'address'
 'afterwards' 'alt.messianic' 'among' 'an' 'and' 'animation' 'anyone'
 'anything' 'anywhere' 'apollo.hp.com' 'are' 'army' 'arromdee' 'article'
 'aspect' 'at' 'atheism' 'atheist' 'average' 'b64635.student.cwru.edu'
 'be' 'beaverton' 'board' 'branch.davidian.compound.waco.tx.us' 'bucaille'
 'bunch' 'but' 'by' 'can' 'captured' 'case' 'caused' 'changed' 'checking'
 'christ' 'colleague' 'commonly' 'cranford' 'crispin' 'current' 'curse'
 'darice' 'day' 'dead' 'depressing' 'did' 'disney' 'dkoresh'
 'dr-pepper.east.sun.com' 'dr.' 'draft' 'early' 'east.sun.com' 'either'
 'even' 'every' 'faith' 'fear' 'feb' 'file' 'find' 'first' 'fly'
 'following' 'followup' 'for' 'fred' 'freedom' 'from' 'galacticentric'
 'genocide' 'geocentrism' 'geoff' 'get' 'god' 'ha' 'have' 'he' 'hear'
 'heart' 'heli

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


you can now compare it with the simple impementation

## Modern problems

Do you enjoy emojis? Well let's see after you find them in your dataset. Lukcly there are libraries that help with this problem.




In [ ]:
import spacy
from spacymoji import Emoji

nlp = spacy.load('en_core_web_sm')
emoji = Emoji(nlp)
nlp.add_pipe("emoji", first=True)

doc = nlp(u"This is a test 😻 👍🏿")
assert doc._.has_emoji == True
assert doc[2:5]._.has_emoji == True
assert doc[0]._.is_emoji == False
assert doc[4]._.is_emoji == True
assert doc[5]._.emoji_desc == u'thumbs up dark skin tone'
assert len(doc._.emoji) == 2
assert doc._.emoji[1] == (u'👍🏿', 5, u'thumbs up dark skin tone')

It's also possible to fix spelling mistakes 

In [ ]:
from spellchecker import SpellChecker

spell = SpellChecker()

print(spell.correction('kword'))

word


## Part-Of-Speech tagging


Somethign we missed so far are information about the role of the words in the sentence. Many words can be used as verb and noun depending on the context. "Help" for example cna be used as a verb: (I help you) or noun (thanks for your help) and if it was stemmed it couls also have been an adjective (helpfull).

Part-Of-Speech (POS) tagging consist on adding some extra information to the word to specify its role in the sentence. 

For Example

I (PRP) eat (VB) pizza (NN)

Where PRP stands for personal pronoun, VB for verb and NN for noun.

Methods: 


- Lexical Based Methods — Assigns the POS tag the most frequently occurring with a word in the training corpus.

- Rule-Based Methods — Assigns POS tags based on rules. For example, we can have a rule that says, words ending with “ed” or “ing” must be assigned to a verb. Rule-Based Techniques can be used along with Lexical Based approaches to allow POS Tagging of words that are not present in the training corpus but are there in the testing data.

- Probabilistic Methods — This method assigns the POS tags based on the probability of a particular tag sequence occurring.
We can distinguish further in 
discriminative methods who try to model the conditional probability distribution, i.e., P(y|x) like SVM, logistic regression and Conditional Random Fields (CRFs)
and generative methods, like naive baise and Hidden Markov Models (HMMs) are probabilistic approaches to assign a POS Tag.

- Deep Learning Methods — Recurrent Neural Networks can also be used for POS tagging.



#### Perceptron tagger in the NLTK package 

We will now see the NLTK implementation of CRF trained using the treebank dataset. Do do that we need to downlaoad the dataset. 

In [ ]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [ ]:
nltk.download('treebank')
nltk.download('universal_tagset')

[nltk_data] Downloading package treebank to /root/nltk_data...
[nltk_data]   Unzipping corpora/treebank.zip.
[nltk_data] Downloading package universal_tagset to /root/nltk_data...
[nltk_data]   Unzipping taggers/universal_tagset.zip.


True

In [ ]:
# The default pos tagger model using in NLTK is maxent_treebanck_pos_tagger
# model, you can find the code in nltk-master/nltk/tag/__init__.py:

nltk.pos_tag('This is an example'.split())

[('This', 'DT'), ('is', 'VBZ'), ('an', 'DT'), ('example', 'NN')]

In [ ]:
import nltk
tagged_sentence = nltk.corpus.treebank.tagged_sents(tagset='universal')
print("Number of Tagged Sentences ",len(tagged_sentence))
tagged_words=[tup for sent in tagged_sentence for tup in sent]
print("Total Number of Tagged words", len(tagged_words))
vocab=set([word for word,tag in tagged_words])
print("Vocabulary of the Corpus",len(vocab))
tags=set([tag for word,tag in tagged_words])
print("Number of Tags in the Corpus ",len(tags))

Number of Tagged Sentences  3914
Total Number of Tagged words 100676
Vocabulary of the Corpus 12408
Number of Tags in the Corpus  12


## Lemmatization

Lemmatization goes a step forward than stemming. It involves the understanding of the role of the words in the sentence.

It relyis generally on Part-Of-Speech (POS) tagging.
POS Tags are useful for building parse trees, which are used in building Name Entity Recogmition's (most named entities are Nouns) and extracting relations between words. It is also essential for building lemmatizers which are used to reduce a word to its root form.

For example meeting/NOUN should be "stemmed" to meeting, not "meet". On the other hand meeting/VERB should be stemmed "meet".


Stememr therefor is better for very specialized domains (medical) or languages that dont have a proper POS dataset.

In [ ]:
# https://spacy.io/api/lemmatizer#lookup
# from spacy.lemmatizer import Lemmatizer
import spacy
from spacy.lookups import Lookups
# This class allows convenient access to large lookup tables and dictionaries, e.g. lemmatization data or 
# tokenizer exception lists using Bloom filters.
lookups = Lookups()
# Add a new table with optional data to the lookups.
# Raises an error if the table exists.
nlp = spacy.load('en_core_web_sm')
# lemmatizer = nlp.add_pipe("lemmatizer")


lookups.add_table({
    "lemma_rules", {
        "noun": ["s", ""], 
        "verb": ["ing", ""]}
                             })
# lemmatizer = lemmatizer.lookup_lemmatize(lookups)
# lemmatizer('books', 'noun')

TypeError: ignored

# Category encoders

A major problem with text is that it does not have all the woderfull properties that numbers have.


There are many methods to transform vategorical data into numeric values, we saw one beofre: CountVectorizer

Convert a collection of text documents to a matrix of token counts

This implementation produces a sparse representation of the counts using scipy.sparse.csr_matrix.


It's possible to specify several parameters for the CountVectorizer, for example if you want to analyze token or words, and if you want to include n_grams which inicates how many consecutive tokens we want to consider.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
help(CountVectorizer)

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(twenty_train.data[:3])
print(vectorizer.get_feature_names_out())


Help on class CountVectorizer in module sklearn.feature_extraction.text:

class CountVectorizer(_VectorizerMixin, sklearn.base.BaseEstimator)
 |  CountVectorizer(*, input='content', encoding='utf-8', decode_error='strict', strip_accents=None, lowercase=True, preprocessor=None, tokenizer=None, stop_words=None, token_pattern='(?u)\\b\\w\\w+\\b', ngram_range=(1, 1), analyzer='word', max_df=1.0, min_df=1, max_features=None, vocabulary=None, binary=False, dtype=<class 'numpy.int64'>)
 |  
 |  Convert a collection of text documents to a matrix of token counts.
 |  
 |  This implementation produces a sparse representation of the counts using
 |  scipy.sparse.csr_matrix.
 |  
 |  If you do not provide an a-priori dictionary and you do not use an analyzer
 |  that does some kind of feature selection then the number of features will
 |  be equal to the vocabulary size found by analyzing the data.
 |  
 |  Read more in the :ref:`User Guide <text_feature_extraction>`.
 |  
 |  Parameters
 |  -----

In [ ]:
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(1, 2))

X2 = vectorizer2.fit_transform(twenty_train.data[:3])
print(vectorizer2.get_feature_names_out())


['14' '14 nntp' '19' '19 feb' '1990' '1990 on' '1993apr19'
 '1993apr19 231641' '1ql0d3' '1ql0d3 5vo' '21652' '21652 monu6' '231641'
 '231641 21652' '31' '31 in' '473' '473 here' '48' '48 articles' '53766'
 '53766 which' '5vo' '5vo dr' 'about' 'about 48' 'about the' 'accepted'
 'accepted notion' 'actor' 'actor plays' 'address' 'address dkoresh'
 'address has' 'afterwards' 'afterwards there' 'alt' 'alt messianic'
 'among' 'among the' 'an' 'an average' 'an interesting' 'an there' 'and'
 'and for' 'and only' 'and scientific' 'and the' 'animation'
 'animation organization' 'animation software' 'anyone' 'anyone tell'
 'anything' 'anything about' 'anywhere' 'anywhere in' 'apollo' 'apollo hp'
 'are' 'are they' 'arizona' 'arizona edu' 'army' 'army draft' 'arromdee'
 'arromdee on' 'article' 'article 1993apr19' 'article 1ql0d3'
 'article 473' 'article 53766' 'articles' 'articles day' 'articles from'
 'as' 'as others' 'aspect' 'aspect of' 'at' 'at the' 'atheism'
 'atheism organization' 'atheist' '

In [ ]:
X2[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 2, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2,
        1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 

In [ ]:
print(X2)

  (0, 229)	1
  (0, 374)	1
  (0, 499)	1
  (0, 331)	1
  (0, 530)	1
  (0, 136)	1
  (0, 372)	1
  (0, 145)	1
  (0, 519)	1
  (0, 171)	2
  (0, 49)	2
  (0, 435)	1
  (0, 532)	1
  (0, 287)	1
  (0, 95)	1
  (0, 431)	1
  (0, 342)	1
  (0, 113)	1
  (0, 52)	1
  (0, 534)	1
  (0, 362)	2
  (0, 54)	1
  (0, 24)	1
  (0, 540)	2
  (0, 511)	1
  :	:
  (2, 561)	2
  (2, 302)	2
  (2, 397)	2
  (2, 410)	2
  (2, 418)	1
  (2, 245)	1
  (2, 285)	1
  (2, 595)	1
  (2, 432)	1
  (2, 57)	1
  (2, 554)	1
  (2, 479)	1
  (2, 43)	1
  (2, 419)	1
  (2, 267)	1
  (2, 433)	1
  (2, 197)	1
  (2, 241)	1
  (2, 195)	1
  (2, 390)	1
  (2, 514)	1
  (2, 290)	1
  (2, 604)	1
  (2, 339)	1
  (2, 578)	1


In [ ]:
print(X2.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 1 ... 1 0 0]
 [1 1 0 ... 0 1 1]]


Recap

we learned the  main operations in an NLP problem:

. 

It's also possible to correct words using packages like autocorrect.

## Excercise

Apply the transformations we just saw to thw fake-news dataset.

In [ ]:
import gensim.downloader as api
# api.info()  # return dict with info about available models/datasets
api.info('fake-news')

# api.info("text8") 

In [ ]:
fn = api.load('fake-news')
for f in fn:
  print(f)

In [ ]:
import pandas as pd
lfn = pd.DataFrame(fn)

lfn.spam_score.astype(float).hist()

In [ ]:
lfn[:1].text. # complete here

In [ ]:
f = lfn[:30].text.apply(word_tokenize).apply(lambda x: [i for i in x if i not in stopwords_list])
# apply(lambda i: set(list(i)) - stopwords)
from gensim.parsing.porter import PorterStemmer
p = # complete here

f.apply(p.stem_documents).apply(nltk.# complete here)


In [ ]:
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))

X2 = vectorizer2  # complete here
print(vectorizer2.get_feature_names())


Now we can write the spam_score into a file

In [ ]:
import io 
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize 
# write the file

 